version: "3.4"
services:
  grosco-frontend:
    build: ../
    ports:
      - 3000:80

  nginx:
    build: ../nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - grosco-frontend
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    command: >
      /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    command: certonly --webroot -w /var/www/certbot --email herock76@gmail.com -d grosco.in -d www.grosco.in --agree-tos --no-eff-email --force-renewal
#   entrypoint: >
#     /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
