version: "3.4"
services:
  grosco-frontend:
    build: ../
    ports:
      - 3000:80

  nginx:
    build: ../nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - grosco-frontend
        #      - certbot
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./var/lib/letsencrypt:/var/lib/letsencrypt
  
  certbot:
    image: certbot/certbot:latest
    volumes:
        - ./etc/letsencrypt:/etc/letsencrypt
        - ./var/lib/letsencrypt:/var/lib/letsencrypt
    command: certonly --webroot -w /var/lib/letsencrypt -d grosco.in --email herock76@gmail.com --agree-tos --no-eff-email --keep-until-expiring -v
