version: "3.4"
services:
  grosco-frontend:
    build: ../
    ports:
      - 3000:80

  nginx:
    build: ../nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - grosco-frontend
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    command: certbot --nginx
  #   command: certbot certonly --webroot-path -w /usr/share/nginx/html -d grosco.in --email herock76@gmail.com --agree-tos --no-eff-email --keep-until-expiring -v
